### ISSUE TITLE
Missing Migration

### ISSUE THREAD

**Issue by rwspielman** [QuickRelease/django-tenants-celery-beat#20]
Looks like the migration `0001_initial.py` was mistakenly left out. This means that it will not work unless the user runs `makemigrations`. This isn't typically run during CI or docker build or anything like that leaving the app broken for production. In an environment like heroku where the file system is reset whenever a dyno restart occurs, the migration will go missing.

**Comment by dave-v** [comment]
Hi, thanks for bringing this up.

It was intentionally left out because it needs to have a ForeignKey to the implementer's own `Tenant` model, so we cannot include the migration. But as you noted, it's not ideal to have to run `makemigrations` during your build step, though this should work fine.

I think what we will do is make that model abstract, and then you can subclass it in your project, which means the generated migration can be dynamic to link to your `Tenant` model and also that the migration will live in your app.

**Comment by dave-v** [comment]
Hi, thanks for bringing this up.

It was intentionally left out because it needs to have a ForeignKey to the implementer's own `Tenant` model, so we cannot include the migration. But as you noted, it's not ideal to have to run `makemigrations` during your build step, though this should work fine.

I think what we will do is make that model abstract, and then you can subclass it in your project, which means the generated migration can be dynamic to link to your `Tenant` model and also that the migration will live in your app.

**Comment by dave-v** [comment]
Until a fix is released, if you add a `makemigrations` step to your build after you've installed the app, that should recreate the migration you need each time.
